### ISSUE TITLE
Request code

### ISSUE THREAD

**Issue by TRX99** [Eclipse-Community/r3dfox-old#271]
Hello

You wrote the following code for me before and it worked correctly.
```

#TabsToolbar {
    background-image: none !important;
  }
```

I recently installed Firefox 138 but this code doesn't work for it. Can you help me figure out how to fix this problem?

I enabled this option as well, but the problem still exists:

toolkit.legacyUserProfileCustomizations.stylesheets -> True

https://github.com/e3kskoy7wqk/Firefox-for-windows-7/releases/tag/138.0-v2

**Comment by krystian3w** [comment]
Maybe the item has a new ID or a new method set some background. The new ID can be changed more easily, the background more difficult.

Theoretically you ate `:root` pseudo-class.  https://github.com/Eclipse-Community/r3dfox/issues/40#issuecomment-2028538306 (I assume a typo with the place of the colon at the end of the line by **`K4sum1`** - I am correcting it in my post)

```css
:root
  #TabsToolbar {
    background-image: none !important;
  }
```

for improved css specificity, duplicating the ID also will work (when it is the method of creating the background with a new method is not a problem):


```css
#TabsToolbar#TabsToolbar {
    background-image: none !important;
}
```

![Image](https://github.com/user-attachments/assets/df3e9dcf-34d3-4f24-8da9-80d045aeebda)
